# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api:
    image: devicewallbackend
    container_name: mobiledevicewall_api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__DefaultConnection: "User ID =postgres;host=postgres_image;password=mobiledevicewall;Port=5432;Database=mobileDeviceWallDB;Pooling=true;"
      DB_CONNECTION_STRING: "host=postgres_image;password=mobiledevicewall;Port=5432;Database=mobileDeviceWallDB;"
    #depends_on: 
    #  - "postgres_image"

  postgres_image:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    ports:
      - "5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    #  - ./init.sql :/docker-entrypoint/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mobiledevicewall"
      POSTGRES_DB: "mobileDeviceWallDB"
  
volumes:
  db_volume:
    
#We can populate the database with initial seed data by adding the following in volumes section.
#volumes:
# — ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql